# Generated by Django 4.2.20 on 2025-03-12 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
