# Generated by Django 4.2.20 on 2025-03-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name_plural': 'Likes'},
        ),
    ]
