"""
Django settings for dating_app project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see:
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os  # ✅ Ajout de l'import manquant
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ⚠️ Sécurité - Mettre DEBUG à False en production
DEBUG = True

# ⚠️ Clé secrète - Ne jamais exposer en production
SECRET_KEY = 'django-insecure-l3ufssa9ogt+u!&s)$%97vb$fwr#(vj-pa25$u9(&^p)*^n9*u'

# Définition des hôtes autorisés
ALLOWED_HOSTS = [
    '127.0.0.1', 
    'localhost',
    'lasamigas-app-e8ea50d13c4b.herokuapp.com'
]

# Origines de confiance pour le CSRF (ajuster selon les besoins)
CSRF_TRUSTED_ORIGINS = [
    "https://lasamigas-app-e8ea50d13c4b.herokuapp.com",
    "http://127.0.0.1:8000"
]

# 📌 Définition des applications installées
INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "chat",
    "rest_framework",
    "django_extensions",
]

# 📌 Configuration pour Django Channels et Redis
ASGI_APPLICATION = "dating_app.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_URL")],
        },
    },
}

# 📌 Middleware
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# 📌 Configuration des URLs
ROOT_URLCONF = "dating_app.urls"

# 📌 Templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Ajout du dossier templates
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# 📌 WSGI
WSGI_APPLICATION = "dating_app.wsgi.application"

# 📌 Base de données SQLite (ajuster si nécessaire)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# 📌 Validation des mots de passe
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# 📌 Localisation et fuseau horaire
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# 📌 Gestion des fichiers statiques
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# 📌 Configuration de Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ]
}

# 📌 Configuration de l'authentification utilisateur
AUTH_USER_MODEL = "users.UserProfile"

# 📌 ID automatique des modèles Django
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
